### ISSUE TITLE
Finalize repo QA compliance

### ISSUE THREAD

**Issue by BTT21000** [api3dao/api-integrations#211]
As part of the TM issue https://github.com/api3dao/tasks/issues/849 for QA, some requirements need to be addressed:

### Repo setup requirements as per [new_repo_creation_checklist.md](https://github.com/api3dao/tasks/blob/main/Technical%20management/Tasks%20documentation/new_repo_creation_checklist.md):
- [x] Write a short description for the repository in the description field
- [x] Add relevant links to the repository link field (e.g. api-integration FE)
- [x] Add the relevant license file `LICENSE.md `consistent with the organizational standards or project requirements. (may change with monorepo requirements)
- [x] Set up Renovate (or Dependabot or a similar tool) for automated security vulnerability scanning to detect vulnerabilities in the codebase. (if not done yet for security)

#### Note: This only applies if the api-integrations package is maintained
- [x] Edit the `README.md` as needed so that it looks well presented on www.npmjs.com, and provides a clear and comprehensive description about the package, including installation instructions, usage examples, and any other relevant information. Package update changesets should not be included in the `README.md`.
- [x] Customize Continuous Integration (CI) workflows to run package-specific tests, linting, and other checks on each commit. Ensure these workflows are optimized for the npm package development cycle. (CI requirements will likely be relocated to the monorepo [data-feeds](https://github.com/api3dao/data-feeds) as per this issue https://github.com/api3dao/tasks/issues/796).
- [x] Review and apply appropriate licenses in `LICENSE.md`.
- [x] Add relevant `package.json` fields as applicable (e.g. such that repo links and keywords show up in NPM, compare [this](https://www.npmjs.com/package/@material/button) to [this](https://www.npmjs.com/package/@api3/ois))
- [x] Verify the setup of security vulnerability scanning tools (e.g. Renovate) for the codebase and dependencies.

**Comment by metobom** [comment]
We completed all the required steps given here. Leaving the issue open just in case if you want to check the repository and make sure.

**Comment by metobom** [comment]
I don't think any keywords are necessary, wdyt @hiletmis?

**Comment by hiletmis** [comment]
It's for private use only. I don't think it's necessary
